"""Regenerate ``_INDEX.md`` files for vault folders (``decisions/``, ``learnings/``).

For ``knowledge/anthropic-docs/`` the scraper owns its own index regeneration
(see :func:`cma.vault.scrape_anthropic_docs.regenerate_index`), and this
module delegates to it.

Idempotent: running twice without intervening changes produces identical bytes.
"""

from __future__ import annotations

import re
from datetime import UTC, datetime
from pathlib import Path

from cma.vault.scrape_anthropic_docs import (
    FRONTMATTER_RE,
)
from cma.vault.scrape_anthropic_docs import (
    regenerate_index as regen_knowledge_index,
)

TITLE_RE = re.compile(r"^# (.+)$", re.MULTILINE)
CREATED_RE = re.compile(r"^created:\s*(\S+)\s*$", re.MULTILINE)
STATUS_RE = re.compile(r"^status:\s*(\S+)\s*$", re.MULTILINE)
TAGS_RE = re.compile(r"^tags:\s*\[(.*?)\]", re.MULTILINE)
REVIEWED_RE = re.compile(r"^reviewed_on:\s*(\S+)\s*$", re.MULTILINE)


def _extract(md_path: Path) -> dict[str, str]:
    """Pull a small dict of fields used by the index renderer."""
    try:
        content = md_path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return {}
    fm = FRONTMATTER_RE.match(content)
    if not fm:
        return {}
    fm_text = fm.group(1)
    body = content[fm.end():]

    out: dict[str, str] = {"slug": md_path.stem, "filename": md_path.name}

    title_match = TITLE_RE.search(body)
    out["title"] = title_match.group(1).strip() if title_match else md_path.stem

    for key, regex in (
        ("status", STATUS_RE),
        ("created", CREATED_RE),
        ("reviewed_on", REVIEWED_RE),
    ):
        m = regex.search(fm_text)
        out[key] = m.group(1).strip().strip('"') if m else ""

    tags_match = TAGS_RE.search(fm_text)
    if tags_match:
        out["tags"] = ", ".join(t.strip() for t in tags_match.group(1).split(","))
    else:
        out["tags"] = ""

    return out


def render_index(target_dir: Path, *, now: datetime | None = None) -> str:
    """Render the markdown for ``target_dir/_INDEX.md``.

    Returns the rendered content (also written to disk). Returns an empty
    string if the target dir doesn't exist.
    """
    if not target_dir.is_dir():
        return ""
    now = now or datetime.now(UTC)
    folder_name = target_dir.name

    rows: list[dict[str, str]] = []
    for md in sorted(target_dir.glob("*.md")):
        if md.name.startswith("_"):
            continue
        info = _extract(md)
        if info:
            rows.append(info)

    lines: list[str] = [
        "---",
        "type: meta",
        "status: active",
        f"created: {now.strftime('%Y-%m-%dT%H:%M:%SZ')}",
        f"updated: {now.strftime('%Y-%m-%dT%H:%M:%SZ')}",
        f"tags: [index, {folder_name}]",
        "related: [[_README]]",
        "confidence: high",
        'source: "auto-generated by cma.vault.index_gen"',
        "---",
        "",
        f"# {folder_name.title()} — Index",
        "",
        "> Auto-generated by `cma vault index`. Do not edit by hand; changes",
        "> will be overwritten on the next run.",
        "",
        "| File | Title | Status | Created | Reviewed | Tags |",
        "|---|---|---|---|---|---|",
    ]

    # Sort: active first, then by created desc (newest first within status).
    # Python's sort is stable, so we sort by the secondary key first, then
    # by the primary.
    status_rank = {"active": 0, "draft": 1, "superseded": 2, "archived": 3}
    rows.sort(key=lambda r: r.get("created", ""), reverse=True)
    rows.sort(key=lambda r: status_rank.get(r.get("status", "active"), 1))

    for r in rows:
        lines.append(
            f"| [{r['filename']}]({r['filename']}) "
            f"| {r.get('title', '')} "
            f"| {r.get('status', '')} "
            f"| {r.get('created', '')} "
            f"| {r.get('reviewed_on', '')} "
            f"| {r.get('tags', '')} |"
        )

    if not rows:
        lines.append("| _(no entries yet)_ |  |  |  |  |  |")

    lines.append("")
    lines.append(f"**Total**: {len(rows)} entries")
    rendered = "\n".join(lines)
    (target_dir / "_INDEX.md").write_text(rendered, encoding="utf-8")
    return rendered


def regenerate_all(vault_root: Path, *, now: datetime | None = None) -> dict[str, int]:
    """Regenerate every ``_INDEX.md`` in the vault. Returns ``{folder: row_count}``."""
    counts: dict[str, int] = {}
    for sub in ("decisions", "learnings"):
        target = vault_root / sub
        if target.is_dir():
            render_index(target, now=now)
            counts[sub] = sum(1 for p in target.glob("*.md") if not p.name.startswith("_"))
    # Knowledge folder has its own index format (scraper-owned).
    anth = vault_root / "knowledge" / "anthropic-docs"
    if anth.is_dir():
        regen_knowledge_index(anth, now=now)
        counts["knowledge/anthropic-docs"] = sum(
            1 for p in anth.glob("*.md") if not p.name.startswith("_")
        )
    return counts
